// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARI0p1Z71lyvAnLZfQATs7WeAWPvrHJx0',
    appId: '1:466125619602:web:57c405363cecdce86f414b',
    messagingSenderId: '466125619602',
    projectId: 'quik-aman-erp',
    authDomain: 'quik-aman-erp.firebaseapp.com',
    storageBucket: 'quik-aman-erp.firebasestorage.app',
    measurementId: 'G-MLC3G47H2L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmvpABsVcV0K3dEXIxC6u1-mekUmJnnas',
    appId: '1:466125619602:android:508c3329e140b11d6f414b',
    messagingSenderId: '466125619602',
    projectId: 'quik-aman-erp',
    storageBucket: 'quik-aman-erp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_4HsLCfHB_jGHXcB3y_6inIFp0RPJwr8',
    appId: '1:466125619602:ios:3222a203e61735026f414b',
    messagingSenderId: '466125619602',
    projectId: 'quik-aman-erp',
    storageBucket: 'quik-aman-erp.firebasestorage.app',
    iosClientId: '466125619602-ddk4jrvi4q6l68hthrcf8atj1aklu0te.apps.googleusercontent.com',
    iosBundleId: 'com.example.genzProtech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_4HsLCfHB_jGHXcB3y_6inIFp0RPJwr8',
    appId: '1:466125619602:ios:3222a203e61735026f414b',
    messagingSenderId: '466125619602',
    projectId: 'quik-aman-erp',
    storageBucket: 'quik-aman-erp.firebasestorage.app',
    iosClientId: '466125619602-ddk4jrvi4q6l68hthrcf8atj1aklu0te.apps.googleusercontent.com',
    iosBundleId: 'com.example.genzProtech',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARI0p1Z71lyvAnLZfQATs7WeAWPvrHJx0',
    appId: '1:466125619602:web:bb18f8eb2d32be9c6f414b',
    messagingSenderId: '466125619602',
    projectId: 'quik-aman-erp',
    authDomain: 'quik-aman-erp.firebaseapp.com',
    storageBucket: 'quik-aman-erp.firebasestorage.app',
    measurementId: 'G-Z7TEQBVD24',
  );

}